<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="wheel_mass" value="0.1"/>
    <xacro:property name="wheel_length" value="0.025"/>
    <xacro:property name="wheel_radius" value="0.025"/>

    <xacro:macro name="wheel" params="link='base_link' prefix='left' reflect offset_x='0' offset_y='0' offset_z='0' *color *gazebo_color">

        <xacro:macro name="shape">
            <origin xyz="0 0 0" rpy="${pi / 2} 0 0"/>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </xacro:macro>

        <xacro:property name="flip" value="1"/>
        <xacro:if value="${prefix == 'left'}">
            <xacro:property name="flip" value="0"/>
        </xacro:if>

        <link name="${prefix}_wheel">
            <visual>
                <xacro:shape/>
                <xacro:insert_block name="color"/>
            </visual>
            <collision>
                <xacro:shape/>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="${link}"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${offset_x} ${reflect * ((offset_y / 2) + (wheel_length / 2))} ${(offset_z / 2) - (wheel_radius / 2)}" rpy="${flip * pi} 0 0"/>
            <axis xyz="0 ${reflect} 0"/>
        </joint>

        <gazebo reference="${prefix}_wheel">
            <xacro:insert_block name="gazebo_color"/>
        </gazebo>

    </xacro:macro>  

</robot>